title: rosalinairl
avatar: https://www.gravatar.com/avatar/30a1018d19fd564c2f7ab690f29bc43d?s=640

accounts:
  -
    name: Twitter
    url: https://twitter.com/rosalinairl
    icon: twitter.svg
  -
    name: YouTube
    url: https://youtube.com/@rosalinairl
    icon: youtube.svg
  -
    name: Twitch
    url: https://twitch.tv/rosalinairl
    icon: twitch.svg
  -
    name: Instagram
    url: https://instagram.com/rosalinairl
    icon: instagram.svg
  -
    name: Bluesky
    url: https://bsky.app/profile/rosalinairl.bsky.social
    icon: bluesky.svg