title: "rosalinairl"
avatar: "https://www.gravatar.com/avatar/30a1018d19fd564c2f7ab690f29bc43d?s=640"

collections_dir: "_collections"
collections:
  accounts:
    output: true
    sort_by: "id"
    permalink: "/:path/"

defaults:
  - scope:
      type: "accounts"
    values:
      layout: "redirect"